Get user's location using geolocation api
MLH-Fellowship/prep-project-22.OCT.PREP.1 pull request #11
Opened 2022-10-11 14:46 UTC by siddhi-244

Resolves #3 
Called the geolocation api in `App.js` and fetched co-ordinates of the user. 

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

2022-10-11 19:01 UTC, Devansu-Yadav requested changes
I mentioned some cosmetic changes, and the rest looks fine. Also, the deploy preview is breaking I guess.

2022-10-11 19:01 UTC, Devansu-Yadav commented on src/App.js
> +    var latitude = position.coords.latitude, longitude = position.coords.longitude;
Better to make use of `const` instead of `var` as a good practice in JS.

2022-10-11 19:01 UTC, Devansu-Yadav commented on src/App.js
> +  function success(position) {
I'd suggest sticking to using Arrow functions for consistency in code.

2022-10-11 19:01 UTC, Devansu-Yadav commented on src/App.js
> +  function success(position) {
The function should be named more appropriately, something like `fetchUserLocation`.

2022-10-11 19:05 UTC, siddhi-244 commented
Will work on these. The project is running fine in the local machine ! @Devansu-Yadav. Let me see what's the issue !

2022-10-11 19:12 UTC, siddhi-244 commented
@Devansu-Yadav Done the changes!

2022-10-12 05:45 UTC, Devansu-Yadav approved these changes
LGTM 👍

2022-10-12 09:02 UTC, akshitadixit commented
![image](https://user-images.githubusercontent.com/56997545/195299529-4540bacb-2b55-44f8-8ba7-0cea759a95fc.png)
@Devansu-Yadav remember to resolve conversations once you're satisfied with that particular change

2022-10-12 09:02 UTC, merged